import{initialFilters,matches,parseRequest,validateCatalog,money,itemsText,proposal}from'./logic.js';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let catalog,filters=initialFilters(),sort='relevance',selected=[],compared=[],checks={},chosen={},dirtyProposal=false,savedProposal='';
const STORAGE='pb-selector-v1';
function readStorage(){try{return JSON.parse(localStorage.getItem(STORAGE)||'{}')}catch{return{}}}
function persist(){try{localStorage.setItem(STORAGE,JSON.stringify({selected,checks,filters,sort,savedProposal,dirtyProposal,chosen}))}catch{toast('Не удалось сохранить на устройстве. Скопируйте текст подборки.')}}
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),3300)}
function get(id){return catalog.products.find(p=>p.id===id)}
function verificationFor(id){const c=checks[id]||{},today=new Date().toLocaleDateString('sv-SE');return{...c,priceConfirmed:!!c.priceConfirmed&&c.priceDay===today,stockConfirmed:!!c.stockConfirmed&&c.stockDay===today}}
function date(s){return new Date(s+'T12:00:00').toLocaleDateString('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric'})}
const status=p=>p.availability==='in_stock'?'В наличии по данным сайта':p.availability==='out_of_stock'?'На сайте нет в наличии':'Наличие уточнить';
const counts={};
function options(values,current,first){return`<option value="">${first}</option>`+values.map(v=>`<option value="${esc(v)}"${current===v?' selected':''}>${esc(v)}</option>`).join('')}
function selectFilter(key,title,values){return`<div class="filter-group"><h3>${title}</h3><select data-filter="${key}" aria-label="${title}">${options(values,filters[key],'Любой вариант')}</select></div>`}
function renderFilters(){
 const brands=['German Grass','Luxberry','Asabella'];
 $('#filters').innerHTML=`<div class="filter-header"><strong>Параметры</strong><button class="filter-close" data-action="closeFilters" aria-label="Закрыть фильтры">×</button></div><div class="filter-group"><h3>Бренд</h3><div class="check-list">${brands.map(b=>`<label class="check-row"><input type="checkbox" data-brand="${b}"${filters.brands.includes(b)?' checked':''}><span>${b}</span><small>${counts[b]||0}</small></label>`).join('')}</div></div>`+
 selectFilter('size','Размер комплекта',['Евро','Полуторный','Семейный'])+
 selectFilter('bundle','Комплектация',['С пододеяльником','С одеялом без пододеяльника'])+
 selectFilter('weave','Плетение / ткань',[...new Set(catalog.products.map(p=>p.weave))].sort())+
 `<div class="filter-group"><h3>Бюджет, ₽</h3><div class="price-row"><input data-filter="minPrice" type="number" min="0" max="10000000" placeholder="От" value="${esc(filters.minPrice)}" aria-label="Минимальная цена"><input data-filter="maxPrice" type="number" min="0" max="10000000" placeholder="До" value="${esc(filters.maxPrice)}" aria-label="Максимальная цена"></div></div>`+
 selectFilter('color','Цвет',[...new Set(catalog.products.flatMap(p=>p.colors))].sort())+
 selectFilter('composition','Материал в составе',['Хлопок','Тенсел','Лён','Шёлк'])+
 selectFilter('sheetType','Простыня',[...new Set(catalog.products.map(p=>p.sheetType))].filter(v=>v!=='Не указано'))+
 `<div class="filter-group"><label class="check-row"><input type="checkbox" data-filter="availableOnly"${filters.availableOnly?' checked':''}><span>В наличии по данным сайта</span></label><p class="filter-note">Остатки необходимо проверить перед предложением клиенту.</p></div><div class="catalog-info"><strong>Каталог от ${date(catalog.generatedAt)}</strong><br>${catalog.products.length} вариантов · 3 бренда<br>Цены сохранены из карточек поставщиков.<br><button data-action="catalog">Данные и обновление</button></div>`;
}
function grouped(){const result=new Map();for(const p of catalog.products.filter(p=>matches(p,filters))){if(!result.has(p.modelId))result.set(p.modelId,[]);result.get(p.modelId).push(p)}let groups=[...result.values()];const min=g=>Math.min(...g.map(p=>p.price??Infinity));if(sort==='priceAsc')groups.sort((a,b)=>min(a)-min(b));else if(sort==='priceDesc')groups.sort((a,b)=>(min(b)===Infinity?-1:min(a)===Infinity?1:min(b)-min(a)));else groups.sort((a,b)=>(a[0].noDuvetCover?-1:1)-(b[0].noDuvetCover?-1:1));return groups}
function render(){
 const groups=grouped(),variants=groups.reduce((s,g)=>s+g.length,0);
 $('#resultCount').innerHTML=`<strong>${groups.length}</strong> моделей · ${variants} вариантов`;
 $('#activeFilters').innerHTML=Object.entries(filters).flatMap(([k,v])=>k==='brands'?v.map(b=>`<button class="chip" data-remove-brand="${esc(b)}">${esc(b)}<span>×</span></button>`):v!==''&&v!==false?`<button class="chip" data-remove-filter="${k}">${esc(k==='minPrice'?'От '+v+' ₽':k==='maxPrice'?'До '+v+' ₽':k==='availableOnly'?'В наличии':v)}<span>×</span></button>`:[]).join('');
 $('#products').innerHTML=groups.length?groups.map(g=>{const p=g.find(p=>p.id===chosen[g[0].modelId])||g.find(p=>p.size==='Евро')||g[0];chosen[p.modelId]=p.id;return`<article class="product-card"><div class="image-wrap"><img class="product-image" src="${esc(p.image)}" alt="${esc(p.displayName||p.name)}" loading="lazy" data-detail="${esc(p.id)}"><span class="image-label">${p.noDuvetCover?'С готовым одеялом':esc(p.weave)}</span><label class="compare-check" title="Добавить к сравнению"><input type="checkbox" data-compare="${esc(p.id)}"${compared.includes(p.id)?' checked':''} aria-label="Сравнить ${esc(p.displayName||p.name)}"></label></div><div class="card-body"><div class="card-brand">${esc(p.brand)}</div><h2 class="card-title">${esc(p.displayName||p.name)}</h2><p class="card-subtitle">${esc(p.colorOriginal||'Цвет не указан')} · ${esc(p.composition)}</p><select class="variant-select" data-variant="${esc(p.modelId)}" aria-label="Размер ${esc(p.displayName||p.name)}">${g.map(v=>`<option value="${esc(v.id)}"${v.id===p.id?' selected':''}>${esc(v.brand==='German Grass'?(v.variantLabel||v.size):v.size)} · ${v.price!==null?money(v.price):'цену уточнить'}</option>`).join('')}</select><p class="card-meta">${esc(p.items[0]?.type)} ${esc(p.items[0]?.size)} см${p.items[0]?.count>1?' · 2 шт.':''}<br>${p.noDuvetCover?'Летнее одеяло, без пододеяльника':p.items.map(i=>i.type).join(' + ')}</p><div class="card-bottom"><div class="card-price"><strong>${p.price!==null?money(p.price):'Цена по запросу'}</strong></div><span class="price-date">Цена сайта · ${date(p.checkedAt)}</span><p class="availability${p.availability==='in_stock'?' available':''}">${status(p)}</p><div class="card-actions"><button data-detail="${esc(p.id)}">Подробнее</button><button class="add-btn${selected.includes(p.id)?' selected':''}" data-add="${esc(p.id)}">${selected.includes(p.id)?'В подборке ✓':'В подборку +'}</button></div></div></div></article>`}).join(''):`<div class="empty"><h2>Точных совпадений нет</h2><p>Попробуйте убрать одно из условий.<br>Каталог пока охватывает ограниченную выборку поставщиков.</p><div class="empty-actions">${['bundle','weave','size','maxPrice','availableOnly'].filter(k=>filters[k]).map(k=>`<button data-remove-filter="${k}">Убрать ${esc({bundle:'комплектацию',weave:'ткань',size:'размер',maxPrice:'лимит цены',availableOnly:'наличие'}[k])}</button>`).join('')}<button data-action="reset">Сбросить всё</button></div></div>`;
 $('#selectionCount').textContent=selected.length;
 const bar=$('#compareBar');bar.hidden=!compared.length;bar.innerHTML=`<div><strong>Сравнение · ${compared.length} из 3</strong><button class="clear-compare" data-action="clearCompare">Очистить</button></div><button class="primary" data-action="compare"${compared.length<2?' disabled':''}>Сравнить товары</button>`;
 persist();
}
function dialog(id,title,body){const d=$(id);d.innerHTML=`<div class="dialog-head"><h2>${title}</h2><button class="close-btn" data-close aria-label="Закрыть">×</button></div><div class="dialog-body">${body}</div>`;if(!d.open)d.showModal();return d}
function specs(p){return`<dl class="detail-specs">${[['Комплектация',p.bundle],['Размер',p.size],...p.items.map(i=>[i.type,`${i.size} см · ${i.count} шт.`]),['Ткань',p.weave],['Состав',p.composition],['Цвет',p.colorOriginal||'Не указан'],['Простыня',p.sheetType],...(p.filling?[['Наполнитель',p.filling]]:[]),...(p.season?[['Сезонность',p.season]]:[])].map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl>`}
function source(p){return`<a class="source-link" href="${esc(p.url)}" target="_blank" rel="noopener noreferrer">Открыть карточку поставщика</a>`}
function detail(id){const p=get(id);if(!p)return;dialog('#detailDialog','Карточка товара',`<div class="detail-grid"><div><img class="detail-photo" src="${esc(p.image)}" alt="${esc(p.displayName||p.name)}"><p class="small" style="margin-top:12px">Фото ${esc(p.brand)} · оттенок на экране может отличаться.</p></div><div><div class="card-brand">${esc(p.brand)} · ${esc(p.sku||'артикул не указан')}</div><h3>${esc(p.displayName||p.name)}</h3><div class="card-price"><strong>${p.price!==null?money(p.price):'Цену уточнить'}</strong></div><p class="small">${esc(p.priceSource)} · ${date(p.checkedAt)}<br>${status(p)}</p>${source(p)}${specs(p)}${p.warnings?.length?`<div class="notice">${p.warnings.map(esc).join('<br>')}</div>`:''}<div class="detail-footer"><button class="primary" data-add="${esc(p.id)}">${selected.includes(p.id)?'Убрать из подборки':'Добавить в подборку'}</button><button data-download="${esc(p.id)}">Скачать фото</button></div></div></div>`)}
function toggleSelection(id){if(!get(id))return;if(selected.includes(id)){selected=selected.filter(v=>v!==id);delete checks[id]}else{if(selected.length>=6)return toast('В одной подборке можно выбрать до 6 товаров.');selected.push(id)}dirtyProposal=false;savedProposal='';render();if($('#selectionDialog').open)selection();if($('#detailDialog').open)detail(id)}
function compare(){dialog('#compareDialog','Сравнение вариантов',`<div class="compare-grid">${compared.map(get).map(p=>`<div class="compare-item"><img src="${esc(p.image)}" alt="${esc(p.displayName||p.name)}"><div><div class="card-brand">${esc(p.brand)}</div><h3>${esc(p.displayName||p.name)}</h3><strong>${p.price!==null?money(p.price):'Цену уточнить'}</strong><p class="small">${status(p)}</p>${specs(p)}${source(p)}<br><button class="primary" data-add="${esc(p.id)}">${selected.includes(p.id)?'В подборке ✓':'В подборку +'}</button></div></div>`).join('')}</div>`)}
function makeProposal(){return'Подобрали для вас следующие варианты:\n\n'+selected.map(id=>proposal(get(id),verificationFor(id))).join('\n\n────────────\n\n')}
function selection(){
 if(!selected.length)return dialog('#selectionDialog','Подборка для клиента','<div class="empty"><h2>Выберите товары</h2><p>Добавьте понравившиеся варианты в подборку,<br>затем подготовьте сообщение клиенту.</p><button data-close class="primary">К каталогу</button></div>');
 dialog('#selectionDialog','Подборка для клиента',`<p class="small">Откройте источник и подтвердите цену нужного размера. Непроверенные цены не попадут в сообщение.</p><div class="selected-list">${selected.map(get).map(p=>{const c=verificationFor(p.id);return`<div class="selection-item"><img src="${esc(p.image)}" alt="${esc(p.displayName||p.name)}"><div><h3>${esc(p.brand)} · ${esc(p.displayName||p.name)}</h3><p>${esc(p.size)} · ${esc(p.items[0].size)} см</p>${source(p)}<div class="verification"><input type="number" min="1" max="10000000" step="0.01" data-price="${esc(p.id)}" value="${esc(c.price??p.price??'')}" placeholder="Цена, ₽" aria-label="Цена для клиента"><label><input type="checkbox" data-confirm-price="${esc(p.id)}"${c.priceConfirmed?' checked':''}>Цена проверена</label><label><input type="checkbox" data-confirm-stock="${esc(p.id)}"${c.stockConfirmed?' checked':''}>Наличие проверено</label></div></div><button class="remove-item" data-add="${esc(p.id)}" aria-label="Убрать товар">×</button></div>`}).join('')}</div><div class="proposal-head"><h3>Сообщение клиенту</h3><button class="minor-btn" data-action="regenerate">Обновить текст</button></div><textarea id="proposal" class="proposal-text" aria-label="Текст предложения клиенту">${esc(dirtyProposal?savedProposal:makeProposal())}</textarea><div class="proposal-actions"><button class="primary" data-action="copy">Копировать текст</button><button data-action="print">Печатная подборка / PDF</button><button data-action="downloadAll">Скачать фотографии</button></div><p class="small" style="margin-top:16px">Текст и фотографии прикрепите в WhatsApp или письмо. Подборка сохраняется на этом устройстве.</p>`);
}
function refreshProposal(){if(!dirtyProposal&&$('#proposal'))$('#proposal').value=makeProposal();else if(dirtyProposal)toast('Вы меняли текст вручную. Обновите в нём цену или нажмите «Обновить текст».');persist()}
async function copy(){const input=$('#proposal');try{await navigator.clipboard.writeText(input.value);toast('Текст скопирован. Можно вставить в WhatsApp или письмо.')}catch{input.focus();input.select();toast('Выделен текст. Нажмите «Копировать» в меню устройства.')}}
async function downloadPhoto(id){const p=get(id);try{const r=await fetch(p.image);if(!r.ok)throw Error();const b=await r.blob(),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=`${p.brand.replaceAll(' ','-')}-${p.sku||p.id}.${b.type.includes('webp')?'webp':b.type.includes('png')?'png':'jpg'}`;a.click();setTimeout(()=>URL.revokeObjectURL(u),5000)}catch{toast('Фото не удалось скачать. Откройте карточку поставщика.')}}
function printSelection(){let el=$('.print-view');if(!el){el=document.createElement('section');el.className='print-view';document.body.append(el)}el.innerHTML=`<h1>Подборка для вас</h1><p>PostelButik · ${new Date().toLocaleDateString('ru-RU')}</p>`+selected.map(get).map(p=>`<article class="print-item"><img src="${esc(p.image)}" alt=""><div><h2>${esc(p.brand)} · ${esc(p.displayName||p.name)}</h2><p>${esc(proposal(p,verificationFor(p.id)).replace(p.url,''))}</p><a href="${esc(p.url)}">${esc(p.url)}</a></div></article>`).join('');window.print()}
function requestDialog(){dialog('#detailDialog','Запрос клиента',`<p class="request-hint">Вставьте запрос. Распознаём размер, ткань, комплектацию, один цвет и бюджет по простым правилам. Проверьте параметры перед применением.</p><textarea id="requestText" placeholder="Нужно постельное бельё евро из сатина с одеялом, которое не нужно заправлять"></textarea><div class="request-controls"><button class="primary" data-action="parse">Выделить параметры</button></div><div id="parsed"></div>`)}
function parsedRequest(){const input=$('#requestText').value,parsed=parseRequest(input);requestDialog.last=parsed;const labels={size:'Размер',weave:'Ткань',bundle:'Комплектация',composition:'Состав',color:'Цвет',maxPrice:'Бюджет до',sheetType:'Простыня'};$('#parsed').innerHTML=Object.keys(parsed).length?`<div class="notice">Проверьте: ${Object.entries(parsed).map(([k,v])=>`${labels[k]}: ${esc(v)}${k==='maxPrice'?' ₽':''}`).join('; ')}.<br>Другие пожелания нужно выбрать вручную.</div><button class="primary" data-action="applyRequest">Применить параметры</button>`:'<div class="notice">Не удалось уверенно выделить параметры. Выберите их в фильтрах.</div>'}
function catalogDialog(){dialog('#detailDialog','Данные каталога',`<p class="small">Выборка от ${date(catalog.generatedAt)}. Поиск работает по сохранённым данным, а не по текущим остаткам сайтов.</p><div class="source-stats">${catalog.sources.map(s=>`<div class="source-stat"><strong>${esc(s.name)} · ${catalog.products.filter(p=>p.brand===s.name).length} вариантов</strong><p>${esc(s.note)}</p></div>`).join('')}</div><div class="data-actions"><button data-action="export">Выгрузить каталог</button><button data-action="import">Загрузить каталог</button><input id="catalogFile" type="file" accept="application/json,.json" hidden></div><p class="small">Импорт принимает каталог в формате этой выгрузки. Некорректный файл не заменит текущие данные. Закрытые прайсы и данные клиентов сюда не загружайте.</p>`)}
async function importCatalog(file){try{if(!file||file.size>10*1024*1024)throw Error('Файл должен быть меньше 10 МБ.');const data=validateCatalog(JSON.parse(await file.text()));try{localStorage.setItem('pb-imported-catalog',JSON.stringify(data))}catch{throw Error('Не хватает места для нового каталога. Старый сохранён.')}catalog=data;selected=[];compared=[];checks={};filters=initialFilters();savedProposal='';dirtyProposal=false;countBrands();renderFilters();render();$('#detailDialog').close();toast('Каталог обновлён.')}catch(e){toast(e.message||'Не удалось прочитать каталог.')}}
function countBrands(){for(const b of ['German Grass','Luxberry','Asabella'])counts[b]=new Set(catalog.products.filter(p=>p.brand===b).map(p=>p.modelId)).size}
function reset(){filters=initialFilters();$('#search').value='';renderFilters();render()}
document.addEventListener('click',async e=>{
 const b=e.target.closest('button,[data-detail],a');if(!b)return;
 if(b.dataset.close!==undefined){b.closest('dialog')?.close();return}
 if(b.dataset.detail){detail(b.dataset.detail);return}
 if(b.dataset.add){toggleSelection(b.dataset.add);return}
 if(b.dataset.download){await downloadPhoto(b.dataset.download);return}
 if(b.dataset.removeFilter){filters[b.dataset.removeFilter]=b.dataset.removeFilter==='availableOnly'?false:'';if(b.dataset.removeFilter==='query')$('#search').value='';renderFilters();render();return}
 if(b.dataset.removeBrand){filters.brands=filters.brands.filter(x=>x!==b.dataset.removeBrand);renderFilters();render();return}
 switch(b.dataset.action){
 case'closeFilters':$('#filters').classList.remove('open');break;
 case'reset':reset();break;
 case'clearCompare':compared=[];render();break;
 case'compare':compare();break;
 case'catalog':catalogDialog();break;
 case'regenerate':dirtyProposal=false;savedProposal='';refreshProposal();toast('Текст обновлён по выбранным товарам.');break;
 case'copy':await copy();break;
 case'print':printSelection();break;
 case'downloadAll':for(const id of selected)await downloadPhoto(id);toast('Фотографии подготовлены к скачиванию.');break;
 case'parse':parsedRequest();break;
 case'applyRequest':filters={...initialFilters(),...requestDialog.last};$('#search').value='';renderFilters();render();$('#detailDialog').close();toast('Параметры применены. Остальные пожелания выберите вручную.');break;
 case'export':{const blob=new Blob([JSON.stringify(catalog,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='postelbutik-catalog.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),5000);break}
 case'import':$('#catalogFile').click();break;
 }
});
document.addEventListener('change',e=>{
 const x=e.target;
 if(x.dataset.brand){filters.brands=x.checked?[...new Set([...filters.brands,x.dataset.brand])]:filters.brands.filter(b=>b!==x.dataset.brand);render()}
 if(x.dataset.filter){filters[x.dataset.filter]=x.type==='checkbox'?x.checked:x.value;render()}
 if(x.dataset.variant){chosen[x.dataset.variant]=x.value;render()}
 if(x.dataset.compare){if(x.checked&&compared.length>=3){x.checked=false;return toast('Можно сравнить до трёх вариантов.')}compared=x.checked?[...new Set([...compared,x.dataset.compare])]:compared.filter(id=>id!==x.dataset.compare);render()}
 if(x.dataset.confirmPrice){const id=x.dataset.confirmPrice,c=checks[id]||{};const input=document.querySelector(`[data-price="${CSS.escape(id)}"]`),price=Number(input.value);if(x.checked&&(!Number.isFinite(price)||price<=0||price>10000000)){x.checked=false;return toast('Укажите корректную цену конкретного варианта.')}checks[id]={...c,price,priceConfirmed:x.checked,priceDay:new Date().toLocaleDateString('sv-SE'),verifiedAt:new Date().toISOString()};refreshProposal()}
 if(x.dataset.confirmStock){const id=x.dataset.confirmStock;checks[id]={...checks[id],stockConfirmed:x.checked,stockDay:new Date().toLocaleDateString('sv-SE')};refreshProposal()}
 if(x.id==='catalogFile')importCatalog(x.files[0]);
});
document.addEventListener('input',e=>{const x=e.target;if(x.dataset.price){const id=x.dataset.price;checks[id]={...checks[id],price:x.value,priceConfirmed:false};const check=document.querySelector(`[data-confirm-price="${CSS.escape(id)}"]`);if(check)check.checked=false;refreshProposal()}if(x.id==='proposal'){savedProposal=x.value;dirtyProposal=true;persist()}});
$('#search').addEventListener('input',e=>{filters.query=e.target.value;render()});$('#sort').addEventListener('change',e=>{sort=e.target.value;render()});$('#reset').onclick=reset;$('#filterBtn').onclick=()=>$('#filters').classList.toggle('open');$('#selectionBtn').onclick=selection;$('#exampleBtn').onclick=()=>{filters={...initialFilters(),size:'Евро',weave:'Сатин',bundle:'С одеялом без пододеяльника'};$('#search').value='';renderFilters();render()};
for(const d of document.querySelectorAll('dialog'))d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}});
async function start(){try{
 let imported;try{imported=JSON.parse(localStorage.getItem('pb-imported-catalog')||'null');if(imported)validateCatalog(imported)}catch{imported=null}
 catalog=imported||validateCatalog(await(await fetch('catalog.json')).json());const saved=readStorage();filters={...initialFilters(),...saved.filters};if(!Array.isArray(filters.brands))filters.brands=[];selected=(Array.isArray(saved.selected)?saved.selected:[]).filter(id=>get(id)).slice(0,6);checks=saved.checks&&typeof saved.checks==='object'?saved.checks:{};sort=saved.sort||'relevance';chosen=saved.chosen||{};savedProposal=saved.savedProposal||'';dirtyProposal=!!saved.dirtyProposal;$('#search').value=filters.query;$('#sort').value=sort;countBrands();renderFilters();render();
 const request=document.createElement('button');request.textContent='Запрос клиента';request.className='request-btn';request.onclick=requestDialog;$('.searchbar').insertBefore(request,$('#sort'));
 if('serviceWorker'in navigator){navigator.serviceWorker.addEventListener('message',e=>{if(e.data?.type==='CATALOG_UPDATED')location.reload()});navigator.serviceWorker.register('./sw.js').then(r=>r.update()).catch(()=>{})}
 if(!navigator.onLine)toast('Вы офлайн. Каталог сохранён, цены и наличие проверьте позже.');
 registerTools();
 }catch(e){$('#products').innerHTML='<div class="empty"><h2>Каталог не загрузился</h2><p>Проверьте соединение и перезагрузите страницу.</p><button onclick="location.reload()">Повторить</button></div>';console.error(e)}}
function registerTools(){const context=document.modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});try{Promise.resolve(context.registerTool({name:'configure_product_filters',title:'Подобрать постельные комплекты',description:'Apply supported product filters to the visible catalogue and return matching variants. Does not send messages or confirm availability.',inputSchema:{type:'object',properties:{size:{type:'string',enum:['','Евро','Полуторный','Семейный']},weave:{type:'string'},bundle:{type:'string',enum:['','С пододеяльником','С одеялом без пододеяльника']},maxPrice:{type:'number',minimum:1,maximum:10000000}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){if(!input||typeof input!=='object'||Array.isArray(input))throw Error('Invalid input');for(const k of Object.keys(input))if(!['size','weave','bundle','maxPrice'].includes(k))throw Error('Unknown filter');if(input.size!==undefined&&!['','Евро','Полуторный','Семейный'].includes(input.size))throw Error('Invalid size');if(input.bundle!==undefined&&!['','С пододеяльником','С одеялом без пододеяльника'].includes(input.bundle))throw Error('Invalid bundle');if(input.weave!==undefined&&!catalog.products.some(p=>p.weave===input.weave)&&input.weave!=='')throw Error('Invalid weave');if(input.maxPrice!==undefined&&(!Number.isFinite(input.maxPrice)||input.maxPrice<1||input.maxPrice>10000000))throw Error('Invalid price');filters={...initialFilters(),...input,maxPrice:input.maxPrice===undefined?'':String(input.maxPrice)};$('#search').value='';renderFilters();render();return{count:catalog.products.filter(p=>matches(p,filters)).length,variants:catalog.products.filter(p=>matches(p,filters)).slice(0,10).map(p=>({id:p.id,brand:p.brand,name:p.displayName||p.name,size:p.size,price:p.price,url:p.url}))}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}}
start();
